# 스프링 애플리케이션 이름 설정
spring.application.name=lms-back

# 데이터베이스 접속 설정 (MariaDB 사용)
spring.datasource.url=jdbc:mariadb://192.168.44.133:3306/lms
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=lms
spring.datasource.password=lms

# 개발 도구 설정 - LiveReload 및 자동 재시작 기능 활성화
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

# 로깅 설정 - MyBatis 및 SQL 로그 출력 설정
logging.level.org.mybatis=DEBUG
logging.level.java.sql=DEBUG
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# MyBatis 매퍼 XML 파일 위치 설정
mybatis.mapper-locations=classpath:mapper/*.xml

# JPA 관련 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 게시판 목록에서 한 페이지에 보여줄 게시글 수
board.pagesize=25

# JWT 관련 설정
jwt.secretKey=a-string-secret-at-least-256-bits-longa-string-secret-at-least-256-bits-long
jwt.validity=1800000

# 파일 저장 경로 설정 (정적 리소스 경로)
saveImgDir=C:/Java/nginx-1.26.3/nginx-1.26.3/html/cdn/
saveSimgDir=C:/Java/nginx-1.26.3/nginx-1.26.3/html/cdn/small/
savePdsDir=C:/Java/nginx-1.26.3/html/cdn/

# 파일 업로드 제한 설정
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=50MB


spring.main.allow-circular-references=true

